### PR TITLE
Add GraphQL Unit Testing

### PR DESCRIPTION
**Pull request by DeathCamel58**
This uses [Insomnia Inso](https://github.com/Kong/insomnia/tree/develop/packages/insomnia-inso) to run CI tests on PRs.

I've set up a couple test sites on my domain [SEOPress Non-Pro](https://wp-graphql-seopress-testing-nonpro.randomcpu.com) and  [SEOPress Pro](https://wp-graphql-seopress-testing-pro.randomcpu.com) to run unit tests against (these sites pull the PRs to update the plugin).

### CODE REVIEW

**Comment by DeathCamel58** [comment]
PHPCS fails because `GH_BOT_TOKEN` isn't defined.

**Comment by DeathCamel58** [comment]
Ref #4

**Comment by moonmeister** [comment]
> PHPCS fails because `GH_BOT_TOKEN` isn't defined.

Screenshot_20210709-080240

Looks like secrets aren't shared with PRs from other forks.  If you add the env to your fork does it work?

**Comment by DeathCamel58** [comment]
That's weird.
Screenshot for test PR in my fork

**Pull request merged**
